version: '3.8'

services:
  php-fpm:
    build: .
    container_name: php-fpm
    restart: unless-stopped
    volumes:
      - ./app:/var/www/html
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./app/public:/var/www/html/public
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      - app-network

networks:
  app-network:
    driver: bridge