{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "php-frontend.fullname" . }}
  labels:
    {{- include "php-frontend.labels" . | nindent 4 }}
spec:
  hosts:
    - {{ .Values.istio.virtualService.hosts | first }}
  gateways:
    - {{ .Values.istio.virtualService.gateways | first }}
  http:
    - route:
        - destination:
            host: {{ include "php-frontend.fullname" . }}
            subset: v1
            port:
              number: {{ .Values.service.port }}
          weight: 90
        - destination:
            host: {{ include "php-frontend.fullname" . }}
            subset: v2
            port:
              number: {{ .Values.service.port }}
          weight: 10
{{- end }}