{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "php-frontend.fullname" . }}-gateway
  labels:
    {{- include "php-frontend.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.istio.gateway.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    {{- with .Values.istio.gateway.selector }}
    {{- toYaml . | nindent 4 }}
    {{- else }}
    istio: ingressgateway
    {{- end }}
  servers:
    {{- range .Values.istio.gateway.servers }}
    - port:
        number: {{ .port.number }}
        name: {{ .port.name | default "http" }}
        protocol: {{ .port.protocol | upper }}
      hosts:
        {{- toYaml .hosts | nindent 8 }}
      {{- if .tls }}
      tls:
        {{- toYaml .tls | nindent 8 }}
      {{- end }}
    {{- end }}
{{- end }}