{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "php-frontend.fullname" . }}
  labels:
    {{- include "php-frontend.labels" . | nindent 4 }}
spec:
  host: {{ include "php-frontend.fullname" . }}
  {{- with .Values.istio.destinationRule.trafficPolicy }}
  trafficPolicy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  subsets:
    {{- range .Values.istio.destinationRule.subsets }}
    - name: {{ .name }}
      labels:
        {{- toYaml .labels | nindent 8 }}
      {{- if .trafficPolicy }}
      trafficPolicy:
        {{- toYaml .trafficPolicy | nindent 8 }}
      {{- end }}
    {{- end }}
{{- end }}