apiVersion: v1
kind: Service
metadata:
  name: {{ include "php-frontend.fullname" . }}
  labels:
    {{- include "php-frontend.labels" . | nindent 4 }}
  {{- if .Values.istio.enabled }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default "http" }}
      protocol: TCP
  selector:
    {{- include "php-frontend.selectorLabels" . | nindent 4 }}