apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "php-frontend.fullname" . }}
spec:
  hosts:
    - php-frontend.retailershakti.com
  gateways:
    - istio-system/istio-gateway
  http:
    - route:
        - destination:
            host: {{ include "php-frontend.fullname" . }}
            subset: v1
            port:
              number: {{ .Values.service.port }}
          weight: 90
        - destination:
            host: {{ include "php-frontend.fullname" . }}
            subset: v2
            port:
              number: {{ .Values.service.port }}
          weight: 10